apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}}-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}-sa
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.name }}-role
  apiGroup: rbac.authorization.k8s.io
