{{- range .Values.rbac.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Values.name }}-binding
  namespace: {{ . }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.name }}-sa
    namespace: {{ $.Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.name }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
